# Lyft bless ssh alias
source /Users/dmortlock/go/src/github.com/lyft/blessclient/lyftprofile

# Go
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

# General alias
alias ls="ls -G"
alias ll="ls -lh"
alias la="ls -a"
alias rm="rm -rf"

# Lyft alias
alias src="cd ~/go/src/github.com/lyft"
alias dotfiles="cd ~/go/src/github.com/lyft/dotfiles"
alias gccup="glide cc && glide up"
alias saltup="salt-call state.highstate"
alias venvm="python3 -m venv vevn3"
alias venva="source vevn3/bin/activate"
alias pipin="pip install -r requirements3.txt --extra-index-url https://pypi.lyft.net/pypi/"
alias pipcomp="control run piptools.compile" # pipcomp <service_name>

# Lyft alias onebox
alias obreset="ssh-keygen -R dmortlock-onebox.dev.lyft.net"
alias obssh="ssh dmortlock-onebox.dev.lyft.net"

# Neovim
export EDITOR="nvim"
alias v=nvim
alias vi=nvim
alias vim=nvim

# The Fuck
eval $(thefuck --alias)
eval $(thefuck --alias FUCK)

# Bash completion
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

# Oh my git
# source ~/.oh-my-git/prompt.sh

# Share history between terminal tabs
export HISTSIZE=50000  # Max history lines in memory
export HISTFILESIZE=50000  # Max history lines on disk
export HISTCONTROL=ignoredups:erasedups  # Ignore duplicate lines
shopt -s histappend  # Append history file instead of overwriting
# After each command, append to the history file and reread it
export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a; history -c; history -r"

