# Go
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

# General
alias ls="ls -G"
alias ll="ls -lh"
alias rm="rm -rf"

# Neovim
export EDITOR="nvim"
alias v=nvim
alias vi=nvim
alias vim=nvim

# The Fuck
eval $(thefuck --alias)
eval $(thefuck --alias FUCK)

# RPI
alias rpi="ssh 192.168.2.2"

